name: Build u-boot for RK3308
run-name: u-boot ${{ inputs.uboot_ref }} for RK3308
on:
  workflow_dispatch:
    inputs:
      uboot_ref:
        description: u-boot ref
        required: true
        default: master
        type: string
      rkbin_ref:
        description: rkbin ref
        required: true
        default: master
        type: string

jobs:
  build:
    name: ${{ matrix.boards.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        boards:
          [
            {
              "name": "rk3308-roc-cc",
              "config": "roc-cc-rk3308_defconfig",
              "uart": "2",
              "iomux": "0",
              "baudrate": "1500000",
            },
            {
              "name": "rk3308-rock-pi-s",
              "config": "rock-pi-s-rk3308_defconfig",
              "uart": "0",
              "iomux": "0",
              "baudrate": "1500000",
            },
            {
              "name": "rk3308-rock-s0",
              "config": "rock-s0-rk3308_defconfig",
              "uart": "0",
              "iomux": "0",
              "baudrate": "1500000",
            },
          ]

    steps:
      - name: Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install gcc-12 gcc-12-aarch64-linux-gnu python3-pyelftools confget libgnutls28-dev

          sudo ln -sf cpp-12 /usr/bin/cpp
          sudo ln -sf gcc-12 /usr/bin/gcc
          sudo ln -sf gcc-ar-12 /usr/bin/gcc-ar
          sudo ln -sf gcc-nm-12 /usr/bin/gcc-nm
          sudo ln -sf gcc-ranlib-12 /usr/bin/gcc-ranlib
          sudo ln -sf gcov-12 /usr/bin/gcov
          sudo ln -sf gcov-dump-12 /usr/bin/gcov-dump
          sudo ln -sf gcov-tool-12 /usr/bin/gcov-tool

          sudo ln -sf aarch64-linux-gnu-cpp-12 /usr/bin/aarch64-linux-gnu-cpp
          sudo ln -sf aarch64-linux-gnu-gcc-12 /usr/bin/aarch64-linux-gnu-gcc
          sudo ln -sf aarch64-linux-gnu-gcc-ar-12 /usr/bin/aarch64-linux-gnu-gcc-ar
          sudo ln -sf aarch64-linux-gnu-gcc-nm-12 /usr/bin/aarch64-linux-gnu-gcc-nm
          sudo ln -sf aarch64-linux-gnu-gcc-ranlib-12 /usr/bin/aarch64-linux-gnu-gcc-ranlib
          sudo ln -sf aarch64-linux-gnu-gcov-12 /usr/bin/aarch64-linux-gnu-gcov
          sudo ln -sf aarch64-linux-gnu-gcov-dump-12 /usr/bin/aarch64-linux-gnu-gcov-dump
          sudo ln -sf aarch64-linux-gnu-gcov-tool-12 /usr/bin/aarch64-linux-gnu-gcov-tool

      - name: Checkout rkbin - ${{ inputs.rkbin_ref }}
        uses: actions/checkout@v4
        with:
          repository: rockchip-linux/rkbin
          ref: ${{ inputs.rkbin_ref }}
          path: rkbin

      - name: Checkout u-boot - ${{ inputs.uboot_ref }}
        uses: actions/checkout@v4
        with:
          repository: Kwiboo/u-boot-rockchip
          ref: ${{ inputs.uboot_ref }}
          path: u-boot

      - name: Build u-boot - ${{ matrix.boards.config }}
        run: |
          DDRBIN=$(confget -f rkbin/RKBOOT/RK3308MINIALL.ini -s LOADER_OPTION FlashData)
          sed -i 's/uart id=/uart id=${{ matrix.boards.uart }}/' rkbin/tools/ddrbin_param.txt
          sed -i 's/uart iomux=/uart iomux=${{ matrix.boards.iomux }}/' rkbin/tools/ddrbin_param.txt
          sed -i 's/uart baudrate=/uart baudrate=${{ matrix.boards.baudrate }}/' rkbin/tools/ddrbin_param.txt
          rkbin/tools/ddrbin_tool rk3308 rkbin/tools/ddrbin_param.txt rkbin/$DDRBIN
          export ROCKCHIP_TPL=../rkbin/$DDRBIN
          export BL31=../rkbin/$(confget -f rkbin/RKTRUST/RK3308TRUST.ini -s BL31_OPTION PATH)
          cd u-boot
          make mrproper
          make ${{ matrix.boards.config }}
          make KCFLAGS="-Werror" CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc)
          tools/mkimage -l u-boot.itb

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.boards.name }}
          path: |
            u-boot/u-boot-rockchip.bin
            u-boot/u-boot-rockchip-spi.bin
